#!/usr/bin/env bash
#Creating a script that uses a while loop to print conditionally
x=1
while [ $x -le 10 ]
do
	if [ $x -eq 9 ]
	then
		echo "Best School"
		echo "Hi"
	else
		echo "Best School"
	x=$(( x + 1 ))
	fi #$x does not exist
done
